{"name": "test_1_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'Login' object has no attribute 'time'", "trace": "self = <tests.test_liquidaciones.TestLiquidaciones object at 0x000001F264B2C3D0>\n\n    def test_1_login(self):\n        driver = self.driver\n        loginUsuarios = Login(driver)\n>       loginUsuarios.loginUsuarioSaes(USER1, PASS1)\n\ntest_liquidaciones.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <src.clases.Login.Login object at 0x000001F264B1E750>, nombreUsuario = 'marcano01', clave = 'Externo$$111'\n\n    def loginUsuarioSaes(self, nombreUsuario, clave):\n        try:\n            self.driver.find_element(By.XPATH, INPUT_LOGIN_USER).clear()\n            self.driver.find_element(By.XPATH, INPUT_LOGIN_USER).send_keys(nombreUsuario)\n>           self.time.sleep(1)\nE           AttributeError: 'Login' object has no attribute 'time'\n\n..\\src\\clases\\Login.py:20: AttributeError"}, "attachments": [{"name": "stdout", "source": "5d33183f-92a2-42a0-9c16-d6f9bc00af35-attachment.txt", "type": "text/plain"}], "start": 1699303794294, "stop": 1699303794442, "uuid": "46366b6b-bd30-4ae6-a723-9898fc0b29bc", "historyId": "5b3ba79e8384a23537063afcc69791d6", "testCaseId": "5b3ba79e8384a23537063afcc69791d6", "fullName": "test_liquidaciones.TestLiquidaciones#test_1_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('test_setup')"}, {"name": "suite", "value": "test_liquidaciones"}, {"name": "subSuite", "value": "TestLiquidaciones"}, {"name": "host", "value": "LAR-PF3K6GME"}, {"name": "thread", "value": "10076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_liquidaciones"}]}